# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townhall', '0002_auto_20171021_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profilepics/'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
